### ISSUE TITLE
Where is the fine-tuning code?

### ISSUE THREAD

**Issue by Moradnejad** [agiagoulas/qa_predictions#1]
Hi,
I wanted to analyze the fine-tuning code. Can you help me with that?

**Comment by agiagoulas** [comment]
Hi @Moradnejad 
I adapted this notebooks for each case: https://github.com/jorgeramirez/bert-qa-colab
I can share you my specific notebooks, that contain not really beautiful code, over Google Drive:
[https://drive.google.com/drive/folders/1JgqtIg0U0M5xRh8rKRCHottmg8vt87ar?usp=sharing](https://drive.google.com/drive/folders/1JgqtIg0U0M5xRh8rKRCHottmg8vt87ar?usp=sharing)
I hope this is helpful to you.
Greeting,
Alex
